version: '2'
services:
  nginx-portal:
    image: nginx:alpine
    volumes:
      - ./example/compose/nginx/portal/nginx.conf:/etc/nginx/nginx.conf
      - ./example/compose/nginx/portal/ssl:/etc/ssl
    ports:
      - "8080:443"
    networks:
      - authelianet
