version: '2'
services:
  mongo:
    image: mongo:3.4
    command: mongod --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=authelia
      - MONGO_INITDB_ROOT_PASSWORD=authelia
    ports:
      - "27017:27017"
    networks:
      - authelianet
