version: '2'
services:
  nginx-backend:
    image: nginx:alpine
    volumes:
      - ./example/compose/nginx/backend/html:/usr/share/nginx/html
      - ./example/compose/nginx/backend/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - authelianet
